version: "3.5"

networks:
	inception:
		driver:
			- bridge

services:
	nginx:
		container_name:
			- nginx
		image:
			- nginx
		ports:
			- "443:443"
		volumes:
			- wp:/var/www/html/wordpress
		restart:
			- always

	wordpress:
		container_name:
			- wordpress
		image:
			- wordpress
		restart:
			- always

	mariadb:
		container_name:
			- mariadb
		image:
			- mariadb
		volumes:
			- wp:/var/www/html/wordpress
		restart:
			- always
		

		
# all containers shoulbe without image