version: "3.5"

networks:
  localhost:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agroup/data/wordpress

  maria_db:
    name: maria_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/agroup/data/mysql

services:
  nginx:
    depends_on:
      - wordpress
    build:
      ./requirements/nginx
    container_name:
      nginx
    image:
      nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/wordpress
    networks:
      - localhost
    restart:
      always

  wordpress:
    depends_on:
      - mariadb
    build:
      ./requirements/wordpress
    container_name:
      wordpress
    image:
      wordpress
    volumes:
      - wordpress:/var/wordpress
    networks:
      - localhost
    restart:
      always

  mariadb:
    build:
      context:
        ./requirements/mariadb
      args:
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
        DATABASE: $MYSQL_DATABASE
    container_name:
      mariadb
    image:
      mariadb
    volumes:
      - maria_db:/var/lib/mysql
    networks:
      - localhost
    restart:
      always

